version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: ejs
    versions:
    - 3.1.5
  - dependency-name: lodash
    versions:
    - 4.17.20
